/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

/*
 * main.c
 * Main Program Body
 *
 *  Created on: Sep 15, 2025
 *      Author: odaig041
 */

//includes
#include "stm32l5xx.h"
#include "stm32l552xx.h"
#include "field_access.h"
#include "gpio.h"

#define RCC RCC_NS
#define LD2_OFF_MSK (GPIO_BSRR_BR7) //mask to set the BSRR reg to low
#define LD2_ON_MSK (GPIO_BSRR_BS7) //mask to set the BSRR reg to high
#define B1_IN_MSK (GPIO_IDR_ID13)

//for ld3 red led
#define LD3_OFF_MSK (GPIO_BSRR_BR9)
#define LD3_ON_MSK (GPIO_BSRR_BS9)

uint32_t iterationCount;

void delay(int count) { //delays the code for a certain time
	for (unsigned int n=0; n<count; n++) {}
}

int main(void) {
	//enable peripheral clock of GPIOB
	RCC->AHB2ENR |= RCC_AHB2ENR_GPIOBEN; //enables the clock for GPIOB
	//configure PB7 in output mode
	MODIFY_FIELD(GPIOB->MODER, GPIO_MODER_MODE7, ESF_GPIO_MODER_OUTPUT); //set the mode of the GPIOB to be an outputs

	//enable peripheral clock of GPIOC
	RCC->AHB2ENR |= RCC_AHB2ENR_GPIOCEN; //enables clock for GPIOC
	//configure PC13 in input mode
	MODIFY_FIELD(GPIOC->MODER, GPIO_MODER_MODE13, ESF_GPIO_MODER_INPUT); //sets the mode of the GPIOC to be an inputs\

	//for red led
	//enable peripheral clock of GPIOA
	RCC->AHB2ENR |= RCC_AHB2ENR_GPIOAEN; //enables clock for GPIOA
	//configure PB9 in output mode
	MODIFY_FIELD(GPIOA->MODER, GPIO_MODER_MODE9, ESF_GPIO_MODER_OUTPUT);

	// turn off ld2
	GPIOB->BSRR = LD2_OFF_MSK; //set the Bit Set/Reset Reg to off which will update the output data reg to 0
	iterationCount=0; //sets baseline num of iterations

	//turn on red led
	GPIOA->BSRR = LD3_ON_MSK;

	while (1) { //loop forever
		delay(3e5);
		if (!(GPIOC->IDR & B1_IN_MSK)) { //check if the button is pressed

			GPIOB->BSRR = LD2_ON_MSK; //set the led to on using the bit set reset reg
			GPIOB->IDR; //10010000

			//turn off red led
			GPIOA->BSRR = LD3_OFF_MSK;
		}
		delay(3e5);
		GPIOB->BSRR = LD2_OFF_MSK; //set the led to off using the bit set reset reg
		GPIOA->BSRR = LD3_ON_MSK; //turn on red LED
		GPIOB->IDR; //10000
		iterationCount++; //just the num of iterations.
	}
}

