/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdio.h>
#include "gpio.h"
#include "systick.h"
#include "alarm.h"

#if 1 // 1 for Part B, 0 for Part A
// ... Part B code
	int main (void)
	{
		printf("Start!\n");
		//initialize apps
		Init_Alarm();

		StartSysTick();

		while (1) {
			//run apps
			Task_Alarm();

			WaitForSysTick();
		}
	}
#else
// ... Part A code
static const Pin_t BlueLED = {GPIOB, 7}; //pin pb7, -> user ld2
static const Pin_t Button = {GPIOC, 13}; //pin PC13 -> User B1

#define BLINK_PERIOD 1000 //1 second
#define B1_IN_MSK (GPIO_IDR_ID13)

static Time_t lastToggle;


static unsigned int loopCount = 0;

int main(void) {
	unsigned int loopCount = 0;

	GPIO_Enable(BlueLED); //WORKING

	GPIO_Mode(BlueLED, OUTPUT); //WORKING

	GPIO_Output(BlueLED, HIGH); //WORKING

	GPIO_Enable(Button);
	GPIO_Mode(Button, INPUT);

	StartSysTick();
	lastToggle = TimeNow();

	printf("Hello World!\n");


	while (1) {
		if (TimePassed(lastToggle) >= BLINK_PERIOD  /2) {
			PinState_t s = GPIO_Input(Button);
			if (!(s)) {
			//if (!(Button.port->IDR & B1_IN_MSK)) {
				printf("Button Not Pressed\n");
				//GPIO_Output(BlueLED, HIGH);
				GPIO_Toggle(BlueLED);
			}
			lastToggle = TimeNow();
			printf("Loop count %u\n", loopCount);
		}
		//msDelay(BLINK_PERIOD / 2);



		//msDelay(BLINK_PERIOD / 2);
		//GPIO_Output(BlueLED, LOW);

		loopCount++;
		WaitForSysTick();
	}
}

#endif


